/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dalsemi_onewire_adapter_PDKAdapterUSB */

#ifndef _Included_com_dalsemi_onewire_adapter_PDKAdapterUSB
#define _Included_com_dalsemi_onewire_adapter_PDKAdapterUSB
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_REGULAR
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_REGULAR 0L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_FLEX
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_FLEX 1L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_OVERDRIVE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_OVERDRIVE 2L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_HYPERDRIVE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_SPEED_HYPERDRIVE 3L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_NORMAL
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_NORMAL 0L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_POWER_DELIVERY
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_POWER_DELIVERY 1L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_BREAK
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_BREAK 2L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_PROGRAM
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_LEVEL_PROGRAM 3L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_NOPRESENCE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_NOPRESENCE 0L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_PRESENCE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_PRESENCE 1L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_ALARM
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_ALARM 2L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_SHORT
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_RESET_SHORT 3L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_NOW
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_NOW 0L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_AFTER_BIT
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_AFTER_BIT 1L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_AFTER_BYTE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_CONDITION_AFTER_BYTE 2L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_HALF_SECOND
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_HALF_SECOND 0L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_ONE_SECOND
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_ONE_SECOND 1L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_TWO_SECONDS
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_TWO_SECONDS 2L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_FOUR_SECONDS
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_FOUR_SECONDS 3L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_SMART_DONE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_SMART_DONE 4L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_INFINITE
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_INFINITE 5L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_CURRENT_DETECT
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_CURRENT_DETECT 6L
#undef com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_EPROM
#define com_dalsemi_onewire_adapter_PDKAdapterUSB_DELIVERY_EPROM 7L
/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    OpenPort
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_OpenPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    ClosePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_ClosePort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    AdapterDetected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_AdapterDetected
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    GetAddress
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_GetAddress
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    Search
 * Signature: (IZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_Search
  (JNIEnv *, jobject, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    TouchBit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_TouchBit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    TouchBitPower
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_TouchBitPower
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    TouchByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_TouchByte
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    TouchBytePower
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_TouchBytePower
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    DataBlock
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_DataBlock
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    Reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dalsemi_onewire_adapter_PDKAdapterUSB
 * Method:    PowerLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dalsemi_onewire_adapter_PDKAdapterUSB_PowerLevel
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
